Use `qp` in Creation Module, add notebook for posterior calculation, fix small errors in LSSTErrorModel
LSSTDESC/rail_attic pull request #105
Opened 2021-10-26 17:01 UTC by jfcrenshaw

The Creation Module now uses `qp` for posterior storage. I also removed the option to include posteriors with the sample, since this makes usage more clear and posteriors aren't stored in the DataFrame anymore. I also abstracted the `Creator` object a little more to keep all the pzflow-specific stuff in `FlowEngine`.

I added a new example notebook showing how to calculate posteriors, including the intricacies of using pzflow to calculate posteriors with error convolution and band marginalization.

Finally, I fixed a small error in `LSSTErrorModel` where if you set `ndFlag` to an integer, e.g. `ndFlag=99`, it would force the entire DataFrame to be of type int, which resulted in e.g. a bunch of 0 errors, which were just truncated floats < 1. I also one more check to the parameter validation to make sure the dictionaries of numbers all contain numbers, and are positive when appropriate

2021-10-29 00:20 UTC, sschmidt23 commented on tests/creation/test_degraders.py
> +    """Check that __repr__ returns a string
For the future, for stuff like this that is pretty clearly trivial and exceedingly unlikely to really benefit from regular testing, I think we're all fine in adding a `#pragma: no cover` to the associated code block and skipping the simple test while still reporting 100% coverage.

2021-10-29 00:33 UTC, sschmidt23 requested changes
Looks good, demo notebooks run.  A couple  minor comments that may or may not require changes, though we should discuss:

-I've been clearing jupyter outputs before committing to the repo just to save some space and keep things a little more clean looking.  Maybe clear the notebook, but generate a rendered html version and include that as well, as Julia did for the `evaluation` demo?

-Given that BandCut can be used to cut on any quantity, should it maybe be renamed to something like QuantityCut or something?  You state it in the demo and the docstring, but people are lazy, and having it called BandCut when it's actually more generic might curtail some potential usage by people that don't read said docstring

-Given that we do expect a population of non-detects in LSST mock data, do you think that we should maybe include some dedicated functionality for non-detect marginalization?  It might be done commonly enough that just having something prewritten that can be called would save some time for those generating the posteriors (I think we can assume that we'll only need to marginalize over one band, and most of the time that band will be u-band, which might simplify things a bit).

2021-11-01 18:37 UTC, jfcrenshaw commented on tests/creation/test_degraders.py
> +    """Check that __repr__ returns a string
Cool I didn't know about that command. I have removed the tests for `__repr__` methods and replaced them with with `#pragma: no cover`

2021-11-01 18:53 UTC, jfcrenshaw commented
> Maybe clear the notebook, but generate a rendered html version and include that as well

Done.

> Given that BandCut can be used to cut on any quantity, should it maybe be renamed to something like QuantityCut

I agree this is a good idea. I will make that change today

> do you think that we should maybe include some dedicated functionality for non-detect marginalization?

I agree in principle. I think we should discuss details during the standup today.

2021-11-02 00:53 UTC, jfcrenshaw commented
I added a default grid for u band marginalization, after checking that it works well for Y1 and Y10 errors. 

Note by default it assumes that the u band is stored as `u` because this is what the u band is named in my demos. However, by default, `LSSTErrorModel` assumes the u band is stored as `lsst_u`, because this is what is was called in the DC1 code. Perhaps we should agree on a default names for the LSST bands, and use these defaults everywhere?

2021-11-02 20:26 UTC, sschmidt23 commented
I agree on the default names, and as a further example, the current estimation codes assume the names are 'mag_{band}_lsst', so some sensible internal defaults will minimize multiple name transforms (note: there is already an issue for this particular one: https://github.com/LSSTDESC/RAIL/issues/47).  Let's create a separate issue for that, or build off of issue #47 and not include it in this PR.

The only thing to do before merging is to clear the outputs on the posterior-demo.ipynb notebook, then I think this is ready to go.

2021-11-02 20:40 UTC, jfcrenshaw commented
I will add a comment about the default naming scheme to [issue 47](https://github.com/LSSTDESC/RAIL/issues/47), and ask that it be generalized to setting naming schemes RAIL-wide



> The only thing to do before merging is to clear the outputs on the posterior-demo.ipynb notebook

Whoops, nice catch! That notebook has now been cleared. Assuming all of the checks pass this last commit, this pull request is ready to be merged.

2021-11-02 20:44 UTC, sschmidt23 approved these changes

2021-11-02 20:44 UTC, merged