fix a bug in the action for coverage and add the test badge to README
LSSTDESC/rail_attic pull request #23
Opened 2020-09-22 09:36 UTC by johannct

quick fix to coverage and esthetic addendum to README

2020-09-22 18:48 UTC, sschmidt23 commented on .github/workflows/main.yml
> +        pytest --cov=./rail --cov-report=xml
Since the tests now live in the directory above the rail package, I think specifying `./rail` rather than `./` means that the tests are not found and do not run, as you can see from the 0.0% coverage when I added the branch to the GitHub action to test that things worked properly.
So, I think we want to stick with `--cov=./`

2020-09-22 18:52 UTC, sschmidt23 commented on .github/workflows/main.yml
> +        pytest --cov=./rail --cov-report=xml
Changing it back to did, indeed, get the tests to run.

2020-09-22 18:54 UTC, johannct commented
hmmm @sschmidt23 ok I see your point, but if you look at BlendingToolKit it has the same organisation, with the `btk` package at the same level as the `tests` level, and still the yaml file has `--cov=./btk` : https://github.com/LSSTDESC/BlendingToolKit/blob/master/.github/workflows/config.yml

2020-09-22 18:55 UTC, johannct commented
so there may be something else to understand..... but clearly the coverage report is dysfunctional for rail.

2020-09-22 18:55 UTC, sschmidt23 requested changes
As noted in comments, specifying --cov=./rail skips the tests that live in the RAIL directory, so I think we want to keep --cov=./ in main.yml.  The coverage badge is working properly.  Before merging, we should remove the issue/2/ci branch from the on: push: in main.yml (I need to look up how to trigger on the current branch and potentially add that in its place).

2020-09-22 18:55 UTC, sschmidt23 commented on README.md
> +![tests](https://github.com/LSSTDESC/BlendingToolKit/workflows/tests/badge.svg)
Badge is working properly.

2020-09-23 03:38 UTC, sschmidt23 commented on .github/workflows/main.yml
> +        pytest --cov=./rail --cov-report=xml
Johann pointed out that the coverage was incorrect: it was counting the test files but not the actual rail files.  This is fixed by running pytest as a package.  I pushed this change and coverage now appears to be functioning properly

2020-09-23 04:59 UTC, johannct reviewed
ok let's try that on master

2020-09-23 05:00 UTC, johannct reviewed
remove afterwards

2020-09-23 05:01 UTC, sschmidt23 approved these changes

2020-09-23 05:06 UTC, merged