Issue/236/obs cond
LSSTDESC/rail_attic pull request #247
Opened 2022-09-06 19:02 UTC by hangqianjun

This is draft pull request for the ObsCondition degrader.

2022-09-07 23:02 UTC, jfcrenshaw commented
@hangqianjun this is looking great! Just a few comments above, plus:
- you should add some small map files that can be used to test the degrader during the Github action
- I think you added all of the yaml's in `tests/data/test_ObsCond` so that you could run tests with different configurations of the degrader? If so, then if you move the parameters explicitly into the degrader like I suggested above, we can remove all of these yamls

2022-09-08 17:56 UTC, jfcrenshaw requested changes

2022-09-08 17:56 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +    Degrader that generates magnitude errors using LSSTErrorModel
Make the first line of the docstring a summary of the degrader. So it should mention that this degrader calculates spatially-varying photometric errors using an input map.

2022-09-08 17:56 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +        obs_config_file=Param(
Rather than pointing to a config file, actually put the parameters into the class.

2022-09-08 17:56 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +        obs_config_file=Param(
You could use 
```python
nside
mask
nYrObs
map_dict
```
where `map_dict` is a dictionary that contains
```python
{
    "m5": {"u": path, ...}, 
    "theta": {"u": path, ...},
}
```

OR you could directly make `m5`, `theta`, etc. parameters

2022-09-08 17:56 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +            # reset the index
Why are you doing this with the indices? Does the error model require that the indices be sequential?

2022-09-08 17:56 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +            # calculate photometric errors for this pixel
This is actually just creating the error model. The errors aren't calculated until line 357 below

2022-09-09 10:10 UTC, hangqianjun commented on rail/creation/degradation/observing_condition_degrader.py
> +            # reset the index
I reset the index because the DataFrame for magnitude errors from LSSTErrorModel has an indexing of 0,1,2.., whereas the looped pixel_cat DataFrame doesn't. Directly concatenate them doesn't return the desired object, but a table with either NaN in magnitudes or NaN in magnitude error. Maybe there is an easier way to deal with this?

2022-09-09 10:12 UTC, hangqianjun commented on rail/creation/degradation/observing_condition_degrader.py
> +            # calculate photometric errors for this pixel
I have changed this to `# creating the error model for this pixel` and then moved the `# calculate the error model for this pixel` above calling `errorModel()`

2022-09-09 10:13 UTC, hangqianjun commented on rail/creation/degradation/observing_condition_degrader.py
> +    Degrader that generates magnitude errors using LSSTErrorModel
I have changed the description to `"""Photometric errors based on observation conditions
    
    This degrader calculates spatially-varying photometric errors 
    using input survey condition maps. The error is based on the 
    LSSTErrorModel from the LSST Overview Paper:
    https://arxiv.org/abs/0805.2366
    
    Example:
    ...`

2022-09-09 16:49 UTC, hangqianjun commented on rail/creation/degradation/observing_condition_degrader.py
> +        obs_config_file=Param(
This has now been implemented.

2022-09-11 17:26 UTC, hangqianjun commented
`observing_condition_degrader.py` has now been updated and the tests are merged into `test_degraders.py`. Is there a temporary way to add the dependence for `healpy` and `photerr`? Otherwise the checks cannot be built.

2022-09-14 17:51 UTC, jfcrenshaw commented on rail/creation/degradation/observing_condition_degrader.py
> +            # reset the index
I fixed the indexing issues in PhotErr, so @hangqianjun has removed these lines from the code

2022-09-14 18:21 UTC, jfcrenshaw approved these changes
Everything looks good to me!

2022-09-14 18:21 UTC, merged