Issue/22/class name
LSSTDESC/rail_attic pull request #26
Opened 2020-09-24 00:58 UTC by sschmidt23

This PR addresses issue #22 to read the class name from the config file.  It also adds functionality to perform multiple code runs from a single config file, which necessitates moving the pz.saveloc outside of the class and back to main.py.  I also added a nonexistent.yaml to test the case where the class name is not actually present in the set of algos.

some of the names in the new "runs" structure of the yaml may not be what everyone will prefer, same with the output filename structure, so those are definitely up for comment/revision.

2020-09-24 10:14 UTC, johannct approved these changes
LGTM : there are a couple of print statements to remove and 2 broader scope comments that may be relevant for this pull request, but I approve it so that there is no block to merge.

2020-09-24 10:14 UTC, johannct commented on examples/configs/trytworuns.yaml
> +    run_params:
@sschmidt23 why do we still need the `run_params` level here? Do you foresee something else under run1 but outside of run_params?

2020-09-24 10:14 UTC, johannct commented on examples/main.py
> +        print(single_run_dict)
remove the print statement

2020-09-24 10:14 UTC, johannct commented on examples/main.py
> +    for single_run_dict in overall_dict['runs'].values():
Brainstorming aloud here : this is ok, but we loose access to the fields `run1` `run2`. I think it is perfectly fine to leave these arbitrary : they are user choices to separate the different config..... But then they also might quickly end up being thought of as identifier strings for each config, and thus we may want to build a mechanism to attach these to their configs, and actually persist the field? I realize that there is an outfile_tag as well, but this translates into a fiilename I presume, and I dislike coding relevant stuff in filenames unless forced.

2020-09-24 10:14 UTC, johannct commented on examples/main.py
> +        print(outfile)
remove print statement

2020-09-24 12:31 UTC, aimalz requested changes
I'm in favor of resolving Johann's comment about parsing the config files with mandatory `run#` by eliminating that layer.

2020-09-24 12:31 UTC, aimalz commented on examples/configs/trytworuns.yaml
> +    run_params:
I assume it's for running multiple test conditions for a single code using one config file.  I think we might want to force one config file per run, though, because each Estimator object corresponds to one config file rather than one run right now, and introducing a mandatory `run#` field seems clunky when we probably won't be using it for the real experiments.

2020-09-25 21:44 UTC, sschmidt23 commented on examples/main.py
> +        print(single_run_dict)
removed

2020-09-25 21:44 UTC, sschmidt23 commented on examples/main.py
> +        print(outfile)
removed

2020-09-25 21:47 UTC, sschmidt23 commented on examples/configs/trytworuns.yaml
> +    run_params:
So based on the discussion this morning, I removed the ability to do multiple runs in a single config and essentially reverted back to the way we had things before.  But, now with the addition of an "output_dir" directory name that is prepended to the output path before the output filename.  That way you can save multiple versions of a code's output without overwriting.  
Is that what we had in mind for the structure?

2020-09-25 21:50 UTC, sschmidt23 commented on examples/configs/trytworuns.yaml
> +    run_params:
Ah, just as I push this, I realize that this could be better organized as Alex stated below, with a directory named for the code and then output files based on the run_id, which does then keep like codes together, let me switch to that instead.

2020-09-25 22:11 UTC, sschmidt23 commented on examples/configs/trytworuns.yaml
> +    run_params:
Ok, new setup has a 'run_name' parameter in the yaml file and creates [outpath]/[code_name]/[run_name].hdf5 output files for each run

2020-09-29 08:34 UTC, johannct commented on rail/estimation/utils.py
> +        os.makedirs(outdir)
Do we want to keep the default `exist_ok=False` for `makedirs`. I think that existence of the directories should not raise an error in this context. See https://docs.python.org/3/library/os.html

2020-09-29 08:36 UTC, johannct requested changes
Do we want to keep the default exist_ok=False for makedirs in utils.py. I think that existence of the directories should not raise an error in this context. See https://docs.python.org/3/library/os.html

2020-09-29 18:19 UTC, sschmidt23 commented on rail/estimation/utils.py
> +        os.makedirs(outdir)
I tested this on my machine (cori is still down so I could not test there), and it did not raise an exception without the flag.  But, you're right, I'll add the flag just to be sure.

2020-09-29 20:14 UTC, johannct approved these changes

2020-09-29 20:15 UTC, johannct approved these changes
LGTM

2020-10-01 14:37 UTC, aimalz approved these changes

2020-10-01 14:38 UTC, merged