Issue/125/add brier metric
LSSTDESC/rail_attic pull request #262
Opened 2022-09-26 22:58 UTC by drewoldag

Added the basic Brier metric assuming an input of Numpy arrays (or Python lists). Also introduced a suite of unit tests for the new metric to get full code coverage. Checked code style with pylint.

2022-09-27 12:11 UTC, delucchi-cmu commented on src/rail/evaluation/metrics/brier.py
> +        qp.ensamble objects into np.array objects.
ensemble?

2022-09-27 12:24 UTC, delucchi-cmu reviewed
Just a minor nit. Otherwise LGTM.

2022-09-27 16:41 UTC, drewoldag commented on src/rail/evaluation/metrics/brier.py
> +        qp.ensamble objects into np.array objects.
Yep, good call. Also prompted me to install a spell checker (Code Spell Checker) in VS code, which immediately found another spelling mistake 🤦

2022-09-27 18:35 UTC, jbkalmbach requested changes

2022-09-27 18:35 UTC, jbkalmbach commented on src/rail/evaluation/metrics/brier.py
> +        return np.mean(
This should be the mean of the sum of the squared value along each row.

2022-09-27 18:35 UTC, jbkalmbach commented on src/rail/evaluation/metrics/brier.py
> +        prediction: NxM array, float
Since each row should be a probability distribution should we have a quick check that they each sum to 1? If it is understood then maybe it's not necessary but it might be helpful to add a check and something here mentioning that.

2022-09-27 18:35 UTC, jbkalmbach commented on src/rail/evaluation/metrics/brier.py
> +        return np.mean(
The output for any size NxM input should be a single score with a minimum value of 0 and a maximum value of 2.

2022-09-27 20:10 UTC, drewoldag commented on src/rail/evaluation/metrics/brier.py
> +        return np.mean(
We just had a quick sync in the meeting room, and thanks for the additional clarification about the way the output will be used. It seems to be the "original definition": https://en.wikipedia.org/wiki/Brier_score#Original_definition_by_Brier

I'll make the required modifications, and update the tests.

2022-09-27 20:11 UTC, drewoldag commented on src/rail/evaluation/metrics/brier.py
> +        prediction: NxM array, float
This seems like a good idea to me. I'll likely include that in the _validate_data method.

2022-09-28 16:27 UTC, drewoldag commented on src/rail/evaluation/metrics/brier.py
> +        prediction: NxM array, float
Updated the docstring here to specify that each row should sum to 1. Also implemented a check in _validate_data that will log a warning if there are rows that don't sum to 1.

2022-09-28 16:50 UTC, drewoldag commented on src/rail/evaluation/metrics/brier.py
> +        return np.mean(
I updated the metric calculation based on your guidance and have pushed a commit for this. If you have a chance to take another look, it would be very much appreciated :)

2022-09-30 18:32 UTC, jbkalmbach approved these changes
Updated metric looks good to me. Thanks for the help adding this in!

2022-09-30 18:34 UTC, merged