docs and public directories
LSSTDESC/rail_attic pull request #39
Opened 2020-12-03 21:44 UTC by sjoudaki

Generated using the commands (added here for completeness):

i) sphinx-apidoc -feo docs rail
ii) sphinx-build docs public/

We obtain two sphinx warnings:

i) WARNING: autodoc: failed to import module 'flexzboost' from module 'rail.estimation.algos'; the following exception was raised: No module named 'flexcode'
ii) checking consistency... /mnt/zfsusers/sjoudaki/railstuff/RAIL/docs/modules.rst: WARNING: document isn't included in any toctree

It seems we might be ok with these as flexzboost is not necessarily part of the fiducial installation of RAIL?

2020-12-03 21:58 UTC, sjoudaki commented
The two files used to generate the rest are docs/conf.py and docs/Makefile.

2020-12-03 21:59 UTC, sjoudaki commented
(conf_testing.py can be removed)

2020-12-15 14:51 UTC, johannct requested changes
I think the `public` dir needs to be removed from git and the pull request. I do not think that we want to ship the result of the doc build with git. If we intend to deploy the doc publicly, then we will need a github actions that does the build and deploy to a public space.

2020-12-15 14:51 UTC, johannct commented on docs/conf_testing.py
> +exclude_patterns = []
Here you can exclude the rst files provoking the warnings I think : https://stackoverflow.com/questions/43801615/python-sphinx-exclude-patterns

2020-12-15 14:51 UTC, johannct commented on docs/index.rst
> +   api
The index page does not seem to be properly rendered. Did I do smthg wrong?
![Screenshot from 2020-12-15 12-37-11](https://user-images.githubusercontent.com/586081/102210329-5381c580-3ed2-11eb-8d82-cb629aaadcf2.png)

2020-12-15 14:51 UTC, johannct commented on docs/index.rst
> +   api
when I click on "view page source" it points to file:///home/cohen/lsst/codes/pipelines/photoz/RAIL/public/_sources/index.rst.txt.... I think the problem is that the index should actually be file:///home/cohen/lsst/codes/pipelines/photoz/RAIL/public/rail.html but the fact that there is a top RAIL repository with the package rail within may trouble sphinx as it is currently configured.

2020-12-15 14:51 UTC, johannct commented on docs/rail.estimation.estimator.rst
> +   :show-inheritance:
Do we want to fix the doc together with this pull request? I see that sphinx does not seem to like blank line; the `estimate` docstring in Estimator class is 
```
"""
        The main run method for the photo-z, should be implemented in
        the specific subclass

        Input:
        ------
        data:
          dictionary of all input data

        Returns:
        --------
        pz_dict:
          dictionary of output photo-z params, must include zmode and
          pdf note: zgrid will still be a class variable for now

        should create photo-z estimates with set names, TBD
        for demo will just be `z_mode`
        """
```
and is rendered only as `Prior settings and/or training algorithm for the individual photo-z method, should be implemented in the subclass`

2021-01-28 15:46 UTC, sjoudaki commented
Here, running:

(base) IT222222:RAIL sjoudaki$ sphinx-apidoc -feo docs .
Creating file docs/setup.rst.
Creating file docs/rail.rst.
Creating file docs/rail.creation.rst.
Creating file docs/rail.estimation.estimator.rst.
Creating file docs/rail.estimation.utils.rst.
Creating file docs/rail.estimation.rst.
Creating file docs/rail.estimation.algos.flexzboost.rst.
Creating file docs/rail.estimation.algos.randomPZ.rst.
Creating file docs/rail.estimation.algos.sklearn_nn.rst.
Creating file docs/rail.estimation.algos.trainZ.rst.
Creating file docs/rail.estimation.algos.rst.
Creating file docs/rail.evaluation.rst.
Creating file docs/modules.rst.


(base) IT222222:RAIL sjoudaki$ sphinx-build docs public/
Running Sphinx v1.7.4
loading translations [en]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
estimator flexzboost not installedimation.algos.flexzboost                                                                                                                                             
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Found classifier randomPZ
Found classifier simpleNN
Found classifier trainZ
reading sources... [100%] setup                                                                                                                                                                        
WARNING: autodoc: failed to import module 'rail.estimation.algos.flexzboost'; the following exception was raised:
No module named 'flexcode'
WARNING: autodoc: failed to import module 'setup'; the module executes module level statement and it might call sys.exit().
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] setup                                                                                                                                                                         
generating indices... genindex py-modindex
highlighting module code... [100%] rail.estimation.utils                                                                                                                                               
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in public.

---

As one can see, runs fine except two warnings, one on flexzboost and one on setup.py.

2021-01-28 15:50 UTC, sjoudaki commented on docs/conf_testing.py
> +exclude_patterns = []
Sounds good, thanks. In the latest conf.py we have a few items there. 

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

Could add more if we wish, but I think it's better to receive warnings on e.g. flexzboost so one is kept aware of it.

2021-01-28 15:52 UTC, sjoudaki commented on docs/index.rst
> +   api
The index file should be working now, looks like this at the moment.

<img width="1090" alt="Screen Shot 2021-01-28 at 4 50 21 PM" src="https://user-images.githubusercontent.com/16611275/106163125-20954780-6189-11eb-99e5-fd7678fcc8a7.png">

2021-01-28 15:57 UTC, sjoudaki commented on docs/rail.estimation.estimator.rst
> +   :show-inheritance:
I think sphinx is generating this exactly as it has been written now, please let me know your thoughts?

2021-01-30 12:03 UTC, johannct reviewed
index.rst is not supposed to  be regenerated?

2021-01-30 12:05 UTC, johannct commented
> index.rst is not supposed to be regenerated?

no it does not appear to be generated....

2021-01-30 13:27 UTC, sjoudaki commented
> > index.rst is not supposed to be regenerated?
> 
> no it does not appear to be generated....

yes, that's right, need to keep this file.

2021-03-29 06:03 UTC, sjoudaki commented
I merged the issue/34/autodoc-debug branch, resolving the MR conflicts in the process so that the version in this branch continues to be functional but minimal. 

@aimalz the issue with the sidebar toggle should also be resolved now. Still need to decide whether we want the creation, estimation, and evaluation subpackages listed on the index page (and if so, resolve why only the contents of creation are shown, and same for the sidebar).

2021-06-05 21:13 UTC, johannct approved these changes

2021-06-05 21:48 UTC, sjoudaki commented
Just adding a comment here that this is now being merged thanks to work by @johannct which led to updates to the files. (and thanks also to @aimalz for earlier updates from his autodoc-debug branch)

2021-06-26 19:06 UTC, merged

2021-06-26 19:12 UTC, sjoudaki commented
This is merged now. Thank you so much again @aimalz and @johannct for all of your efforts on this PR! Minor note for the future: if we want to revive the "Edit on GitHub" button (which we decided to remove given Slack discussion), then this is achieved by simply removing the breadcrumbs.html file in the _templates directory.