Issue/45/inform option
LSSTDESC/rail_attic pull request #46
Opened 2021-01-13 00:25 UTC by sschmidt23

This simple PR addresses one isolated portion of issue #45 (the main one, but discussion in that issue grew beyond the specific topic).  It adds a new `inform_options` dictionary to the yaml config file that control whether to write out a trained model or read in a trained model if a pre-trained model exists.  This PR does *not* address the provenance concerns that come with creating/ingesting pre-trained models, that will be left for a future update following discussions of what provenance tracking system that we want to use.

I added tests that create a model and then compare the outputs when ingesting that model vs an initial run, so it looks like everything functions as it should.

2021-01-30 10:27 UTC, johannct requested changes
thanks for this Sam, let's try to have a quick turnaround on my comments. I am available to pair code if we find a good time (though next week is going to be tough)

2021-01-30 10:27 UTC, johannct commented on .github/workflows/main.yml
> +    branches: [ issue/45/inform_option ]
change that on final push of course

2021-01-30 10:27 UTC, johannct commented on examples/main.py
> +        pz.inform()
Can we have a little doc somewhere (README of estimation?) explaining the logic : I was expecting the contrary (run_model true by defualt, and if set to false then load model). It is arbitrary of course, so just a doc to explain the API decision would be useful. This is where one can appreciate the power of C enums, and what a pain it is that python does not have a clean mechanism for it

2021-01-30 10:27 UTC, johannct commented on rail/estimation/estimator.py
> +
Sam, I am not sure about that.... The code you put in flexzboost and sklearn_nn seems rather boilerplate, so why not put it here, and overwrite with a pass randomPZ as you did, when it is not applicable. In the end all these code need to actually move out of estimation actually, as we want to centralize IO; but that may be left for a later stage

2021-01-30 10:27 UTC, johannct commented on tests/test_algos.py
> +    both datasets.
I wonder if it would not be better to have a dedicated test for loading, for saving, etc.... I understand it is painful, if you want I can implement it to finsih the review. I am afraid that quickly the test calls become too complex to easily point to regression issues in the future.

2021-01-30 10:27 UTC, johannct commented on rail/estimation/algos/flexzboost.py
> +        if self.inform_options['save_train']:
we need some boilerplate here, unfortunately, to check early (before starting to train) that modelfile is provided if save_train or load_train is True. I just experienced wasting training time by ending with:
```
finding best sharpen parameter...
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main(sys.argv)
  File "main.py", line 43, in main
    pz.inform()
  File "/home/cohen/lsst/codes/pipelines/photoz/RAIL/rail/estimation/algos/flexzboost.py", line 147, in inform
    with open(self.inform_options['modelfile'], 'wb') as f:
KeyError: 'modelfile'
```

2021-01-30 10:27 UTC, johannct commented on rail/estimation/algos/flexzboost.py
> +    def load_pretrained_model(self):
what code is in charge of calling `load_pretrained_model`, and based on which set of parameters? In the tests we probably need to exercise : 1/ train and stop (no estimate); 2/ train and estimate; 3/ load and estimate;

2021-03-24 21:52 UTC, sschmidt23 commented on examples/main.py
> +        pz.inform()
I think a jupyter notebook that will be added with issue #51 will take care of this, having examples written out in a notebook I think will suffice, but I'll say lets leave it for that separate issue.

2021-03-24 21:58 UTC, sschmidt23 commented on tests/test_algos.py
> +    both datasets.
Separate tests for loading and saving would be good, this test was more for actually checking that the results from loading a trained model agree with the results from computing the model.  Were you thinking of e.g tests where self.modelfile is not defined and such?

2021-03-24 23:26 UTC, sschmidt23 commented on .github/workflows/main.yml
> +    branches: [ issue/45/inform_option ]
will fix this once the PR is accepted

2021-03-24 23:27 UTC, sschmidt23 commented on rail/estimation/estimator.py
> +
I moved the 'boilerplate' to estimator.py and put a note that subclasses can overwrite if they are loading something other than a pickle file

2021-03-24 23:28 UTC, sschmidt23 commented on rail/estimation/algos/flexzboost.py
> +        if self.inform_options['save_train']:
I added a check in the __init__ for the two codes that write out a model, and similarly put a check on the modelfile in estimator.py in load_pretrained_model to check that the `modelfile` keyword is there and that the file exists.  These are not currently covered by the tests, which is related to your comment above about separate tests, I think.

2021-03-24 23:31 UTC, sschmidt23 commented on rail/estimation/algos/flexzboost.py
> +    def load_pretrained_model(self):
I was reworking this a bit in separate branch, but load_pretrained_model is handled in main.py currently, and yes, separate tests are probably necessary.  I wasn't thinking of "train and stop" as an option, but I guess that is a potential use case.

2021-03-24 23:33 UTC, sschmidt23 commented on rail/estimation/algos/flexzboost.py
> +        if self.inform_options['save_train']:
We can add tests of coverage once you confirm that this answers your initial comment

2021-03-29 10:37 UTC, johannct commented on .github/workflows/main.yml
> +    branches: [ issue/45/inform_option ]
sure

2021-03-29 10:38 UTC, johannct commented on examples/main.py
> +        pz.inform()
ok can you put a note there?

2021-03-29 10:40 UTC, johannct commented on tests/test_algos.py
> +    both datasets.
I was thinking of all the cases where codecov notices lack of coverage : try/except blocks on loading and saving pretrained estimators

2021-03-29 10:40 UTC, johannct approved these changes
LGTM, just these items :

2021-03-29 22:16 UTC, sschmidt23 commented on tests/test_algos.py
> +    both datasets.
I just added tests that I think cover all the examples of saving and loading (the one_algo function saves a model, then loads the model and compares the two outputs, so save/load is tested in the course of that), plus tests checking the try/except for missing keys and files that weren't covered before.  So, I think we're now good.

Can you take a quick look and see if there are any cases that I've missed?  codecov is happy, but I'm trying to think if there might be an additional missing use case.

2021-03-29 22:16 UTC, sschmidt23 commented on rail/estimation/algos/flexzboost.py
> +        if self.inform_options['save_train']:
coverage tests were added so I'll resolve this

2021-03-29 22:19 UTC, sschmidt23 commented
I added a note on issue #51 and added some new tests.  @johannct can you take one quick look at the tests to see if I've covered everything from a user point of view, I think I have but a quick eye on the code to be sure is good.  Once you sign off I'll resolve the merge conflict and merge.

2021-03-30 07:03 UTC, johannct commented on tests/test_algos.py
> +    both datasets.
LGTM thanks Sam. Remember to modify the action as well (to push on master)

2021-03-30 20:08 UTC, merged