Issue/49/delight
LSSTDESC/rail_attic pull request #57
Opened 2021-03-29 12:08 UTC by sylvielsstfr

I think it is time to proceed to do a merge  of delightPZ in master.

The merging is purely functionnal. It means Delight hyper parameters are not optimized for test-DC2 dataset. I will need RAIL metrics for this or doing something else.

Note to integrate Delight with DESC it is necessary to review https://github.com/sylvielsstfr/Delight

A first step is to install the Delight branch desc_rail here  https://github.com/sylvielsstfr/Delight/tree/desc_rail in 
https://github.com/LSSTDESC

Then most of the work of interfacing Delight with RAIL can be found in:

https://github.com/sylvielsstfr/Delight/tree/desc_rail/interfaces/rail

where it is possible to read the README.md file.

Let me know when you are ready for presenting/introducing  how all this stuff works.

Sylvie

2021-04-07 21:32 UTC, johannct requested changes
@sylvielsstfr ok very first look at it. There is a lot to digest! Would it be possible to add some basic unit tests so that we clear some of the codecov warnings, and we get to see a bit better the basic functionalities?

2021-04-07 21:32 UTC, johannct commented on examples/HowToDelightPZ.md
> +
in DESC we are advocating to avoid --user as it is extremely fragile. If the packages are not conda installable, one should still work in a conda env and run pip within this env, without --user

2021-04-07 21:32 UTC, johannct commented on examples/HowToDelightPZ.md
> +
It is probably not a good idea even if it is a lot of code. And the copying of the utils.py file in Delight, which anyway is going to be deprecated, is a red flag.

2021-04-07 21:32 UTC, johannct commented on tests/data/parametersTest.cfg
> +numCoefs: 15
Problem with personal path here

2021-04-07 21:32 UTC, johannct commented on tests/data/parametersTest.cfg
> +names: El_B2004a Sbc_B2004a Scd_B2004a SB3_B2004a SB2_B2004a Im_B2004a ssp_25Myr_z008 ssp_5Myr_z008
personal path

2021-04-07 21:32 UTC, johannct commented on rail/estimation/algos/delightPZ.py
> +from interfaces.rail.getDelightRedshiftEstimation import *
We probably need to move most of these to RAIL

2021-06-04 16:46 UTC, aimalz commented
Are these changes being reflected in [the DESC fork of Delight](https://github.com/LSSTDESC/Delight/pull/3)? I think it would be easier to make the changes there and then have RAIL just install and call from that code, no?

2022-04-15 18:31 UTC, closed without merging