Issue/64/bpz addresses  issue #64
LSSTDESC/rail_attic pull request #70
Opened 2021-06-17 21:13 UTC by sschmidt23

This PR adds `bpz_lite`, a simplified subset of BPZ functionality, to RAIL.  It uses some functions from a new `DESC_BPZ` (https://github.com/LSSTDESC/DESC_BPZ) package that I added, and which is now included in the `setup.py`.  A lot of the code is taken from BPZPipe, but I also added back in some features that were missing, e.g. the ability to compute AB files if they are not present.  Adam Broussard also identified a bug in Madau reddening in (pretty much all version of) BPZ, I implemented a change to `DESC_BPZ` that fixes that problem.  Whoever reviews this PR may also want to look at the `DESC_BPZ` package, it's basically just a slight rearrangement of the python3 version of BPZ that we have been using but reorganized to look more like a python package.

Major features: 
- I added a new folder: `rail/estimation/data` to the directory structure that contains subdirectories `FILTER` containing the Filter transmission files, and `SED` containing the SED template files.  Template-based codes should be able to read from this location, that way we can specify *exactly* which SEDs and FILTERs are being assumed when running the code (as opposed to codes that grab data from an outside location that is hardcoded somewhere else).  There is also an `AB` directory that is needed by `bpz_lite` to store some temporary files.  
- A few new config files are needed by BPZ, which are now in rail/estimation/configs/test_bpz.columns(specifies the filters and photometry to use) and rail/estimation/data/SED/CWWSB.list (specifies the SEDs to use)
- For now I only copied the traditional "CWWSB" SEDs to the directory, we can of course add additional SED templates in the future, but this keeps things lightweight.
- I added the LSST filter curves that were assumed when constructing cosmoDC2 to rail/estimation/FILTER.  There are other slightly different versions of LSST filters floating around, so we'll need to be careful to keep track of the exact filter set that is assumed for different data.

2021-06-21 08:14 UTC, johannct requested changes
- I think that `base.yaml` is now broken :  the paths to trainfile and testfile need to go two level up : `../../`
- irrespective of what the structure will eventually be and how we will deal with provenance, the new dirs AB, SED, FILTERS need each a README.md file explaining where the various files come from and what there nominal usage is. Else in the interim this may still drive us crazy.
- 3 files have a conflict to solve.
Thanks a lot for all this! Let's clean the comments fast so that we can approve.

2021-06-21 08:14 UTC, johannct commented on examples/estimation/base.yaml
> +  output_format: qp
It is probably fine and the easier path, but I still ask so that it is documented with the PR : is it necessary or even a good thing to throw qp integration in with this PR?

2021-06-21 08:14 UTC, johannct commented on examples/estimation/configs/BPZ_lite.yaml
> +run_params:
see #71

2021-06-21 08:14 UTC, johannct commented on examples/estimation/configs/simpleNN.yaml
> +  width: 0.025
is that change justified? it is currently one of the 3 conflicts blocking the merge

2021-06-21 08:14 UTC, johannct commented on examples/estimation/configs/test_bpz.columns
> +#Filter        columns  cal(AB or Vega,optional)  zp_error  zp_offset
add a comment header to shortly explain what this file is used for

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +            self.data_path = datapath
check path validity

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +                model_path = os.path.join(data_path, "AB", model)
define AB dir at like 188 or even immediately after data_path definition, so that if we decide to move these dirs around the hardcoded changes in the file will be easier to track down.

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import ABflux
I do not mean to review DESC_BPZ, but is it still necessary to have the `_py3` here?

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +
This acknowledgement should be in DESC_BPZ, together with any licensing information.

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +            P = prior(z, mag_0, prior_file, nt, ninterp=0)  # hardcode interp 0
I would write a `set_prior` function, just in case this step becomes more involved with time. I could imagine a user literally providing his/her own python module after all. And this will probably occur anyway when `inform` is implemented.

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import p_c_z_t, prior
is it really a good thing to import here rather than at the top of the file? Is it even PEP8 compliant? I never remember.....

2021-06-21 08:14 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +
ok the for loop obviously will go away, and its proper multi-core/node distribution should be taken care of by the base class logically. For the time being, I would recommend bringing `self.flux_template` to local scope only once (I think calling `self.` repeatedly is an overhead), and extracting the test_data columns in one shot, and then define the loop as `for i,m0,f,fe in enumerate(zip(m0_col,f_col,fe_col):` or something like that

2021-06-21 08:14 UTC, johannct commented on setup.py
> +                      'DESC_BPZ @ git+https://github.com/LSSTDESC/DESC_BPZ',
any chance you can take the time to turn it into a pip installable package?

2021-06-21 08:16 UTC, johannct commented on examples/estimation/configs/BPZ_lite.yaml
> +  columns_file: ./TMPBPZ/test.columns
this seems to be needed but is not provided in the current branch

2021-06-21 22:02 UTC, sschmidt23 commented on examples/estimation/base.yaml
> +  output_format: qp
I flipped this default while doing some testing and forgot to change it back, I'll revert it back to `old` now.

2021-06-21 22:04 UTC, sschmidt23 commented on examples/estimation/configs/simpleNN.yaml
> +  width: 0.025
I was playing with some tests and didn't mean to commit this change, reverting.

2021-06-21 22:06 UTC, sschmidt23 commented on examples/estimation/configs/test_bpz.columns
> +#Filter        columns  cal(AB or Vega,optional)  zp_error  zp_offset
comment added

2021-06-21 22:08 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import ABflux
It's a remnant from when Will Hartley was working on the update, I think.  It does distinguish it from the py2 version that is floating around.  I'm not bothered by it, but I also wouldn't mind removing the _py3 from filenames.

2021-06-21 22:08 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
It actually belongs in both, as some of the BPZ code functionality is copied in bpz_lite as well.  I do need to add more specific acknowledgements to DESC_BPZ after I email Dan Coe to ask a couple of questions.

2021-06-21 22:10 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +            P = prior(z, mag_0, prior_file, nt, ninterp=0)  # hardcode interp 0
BPZ already reads in a prior from a file specified in the header: the code defines prior as an import from a specific file name, so this already functions as if it was `set_prior` rather than just `prior`

2021-06-21 22:10 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import p_c_z_t, prior
This is left over from some code that Joe Zuntz wrote, but yes, I'll move all imports to the top of the file.

2021-06-21 22:15 UTC, sschmidt23 commented on setup.py
> +                      'DESC_BPZ @ git+https://github.com/LSSTDESC/DESC_BPZ',
I asked Alex about this, I think the consensus was that not all installable packages need to be on PyPI, this setup pulling from GitHub seems to work, so we may leave it in that form rather than insisting on all packages being on PyPI.

2021-06-21 22:17 UTC, sschmidt23 commented on examples/estimation/configs/BPZ_lite.yaml
> +  columns_file: ./TMPBPZ/test.columns
Ah, this was renamed in an internal reorganization that I did and I missed it.  Changing the columns file to point to examples/estimation/configs/test_bpz.columns

2021-06-21 23:39 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import p_c_z_t, prior
Ah, trying to change this reminded me why the imports are structured like this: bpz_tools_py3 requires that an environment variable be set, which happens in the __init__.  If the imports to bpz_tools_py3 are at the top of the file, an exception occurs because the variable has not yet been set.  

So, I reverted the changes and moved the imports back to within the functions in bpz_lite.

2021-06-21 23:56 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
The for loop is only looping over the subset passed to the code in each chunk, e.g. 1000 galaxies out of ~21,000 in the example test data, so I don't think it will go away.  For flux_template, I don't think that the speed loss is fairly minor, and not worth making a copy locally, though we can try it and see.  For the other variables, I find this form much more readable, and I think it involves less copying of data, since we're only grabbing one row of the test_data, rather than copying the whole thing over and enumerating those.

2021-06-22 06:50 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import ABflux
as you like. Maybe an issue to open for the next round of improvement?

2021-06-22 06:51 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +
oh then the acknowledgement and licensing needs to be a bit more formal, then.

2021-06-22 06:52 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +            P = prior(z, mag_0, prior_file, nt, ninterp=0)  # hardcode interp 0
hmm I have a hard time following the code here, especially in the context of an implementation of `inform`.....

2021-06-22 06:55 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import p_c_z_t, prior
ok..... sounds like hiding a problem though...

2021-06-22 06:58 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +
ti should be a view, not a copy. But I am no numpy memory contiguity either. I just learned the hard way to work column wise as much as possible, and loop over rows only when strictly necessary. As a matter of fact the called function could take arrays as argument, rather than floats. This would move the for loop closer to actual computations

2021-06-22 07:00 UTC, johannct commented on setup.py
> +                      'DESC_BPZ @ git+https://github.com/LSSTDESC/DESC_BPZ',
DESC CO may insist....

2021-06-22 18:21 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
The original BPZ code has no license file.  I'm about to email Dan Coe about the Madau bug fix in DESC_BPZ, I'll also ask if it's ok that we have messed with the code, and also about posting to PyPI.  Again, this being a modification of a public code with no official license is an uncomfortable area of space to be in.  I think there may be similar issues with other codes, e.g. Delight with similar issues (though I don't know what license info Delight has).

2021-06-22 18:23 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +            P = prior(z, mag_0, prior_file, nt, ninterp=0)  # hardcode interp 0
This is the way the original code was set up, again, the goal here was to do a minimal port of BPZ, and this is how BPZ is written.  For inform, I think it will entail running a custom fit to find the ~14 parameters, and then a special prior function that somehow reads in those parameters.  I haven't worked out exactly how I wanted to do that yet, which is why `inform` remains unimplemented.

2021-06-22 18:24 UTC, johannct commented on rail/estimation/algos/bpz_lite.py
> +
Yes let's try to clean things up. The advantage with Delight is that Boris is in DESC.

2021-06-22 18:25 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import p_c_z_t, prior
Yes, I agree, though the way the original code was written this is how things work.  There's a similar issue with the prior, as the name of the .py file that it imports `prior` from is also in the config file.

2021-06-23 23:18 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +            self.data_path = datapath
added a check

2021-06-23 23:41 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
Ok, I pulled out the two `self.` references in the loop and also changed this to a list comprehension rather than a for loop.

2021-06-23 23:43 UTC, sschmidt23 commented on setup.py
> +                      'DESC_BPZ @ git+https://github.com/LSSTDESC/DESC_BPZ',
Ok, but that issue is beyond this PR, we can create a separate issue somewhere, as this same issue is also true for qp as at least one other RAIL dependency.

2021-06-23 23:44 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
I'm waiting on a reply from Dan Coe, but again, this is an issue for DESC_BPZ rather than bpz_lite, so is there anything remaining to be done here?

2021-06-23 23:44 UTC, sschmidt23 commented on examples/estimation/configs/BPZ_lite.yaml
> +run_params:
Should we deal with this separate from this PR, as it applies to every yaml file in configs?

2021-06-23 23:57 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +
Any combo of the loop looked uglier and less comprehensible to me than the original for loop, and the original loop is also closer to the original BPZ code, so I switched it back.  I did store local copies of the two self variables that are called in the loop, which should save a small amount of time.

2021-06-24 00:34 UTC, johannct commented on setup.py
> +                      'DESC_BPZ @ git+https://github.com/LSSTDESC/DESC_BPZ',
yes

2021-06-24 00:51 UTC, johannct approved these changes

2021-06-24 00:54 UTC, sschmidt23 commented on rail/estimation/algos/bpz_lite.py
> +        from desc_bpz.bpz_tools_py3 import ABflux
I'll create an issue on DESC_BPZ and mention the renaming

2021-07-09 20:08 UTC, sschmidt23 commented
I heard back from Dan Coe via email, he wasn't sure of which License to use and CC'd Noel Benitez on the email (though Benitez has apparently left the field).  I'm not sure how long it will take to hear back on the License issue, which is really an issue for DESC_BPZ not RAIL, so I'm going to resolve the conflict and try to merge this in now, and we can worry about the incomplete readthedocs later.

2021-07-09 20:31 UTC, merged